name: run-tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
        laravel: [6.*, 7.*, 8.*, 9.*, 10.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          -   laravel: 10.*
              testbench: 8.*
          -   laravel: 9.*
              testbench: 7.*
          -   laravel: 8.*
              testbench: 6.*
          -   laravel: 7.*
              testbench: 5.*
          -   laravel: 6.*
              testbench: 4.*
        exclude:
          - php: 7.2
            laravel: 8.*
          - php: 7.2
            laravel: 9.*
          - php: 7.2
            laravel: 10.*
          - php: 7.3
            laravel: 9.*
          - php: 7.3
            laravel: 10.*
          - php: 7.4
            laravel: 9.*
          - php: 7.4
            laravel: 10.*
          - php: 8.0
            laravel: 10.*
          - php: 8.0
            laravel: 8.*
          - php: 8.1
            laravel: 6.*
          - php: 8.1
            laravel: 7.*
          - php: 8.1
            laravel: 8.*
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Execute tests
        run: vendor/bin/phpunit
